name: Build, test and deploy backend

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test-package:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build and test with Maven
        run: mvn -B package --file pom.xml

      - name: Prepare JAR for upload
        run: mkdir build && cp target/*.jar build

      - name: Upload resulting JAR
        uses: actions/upload-artifact@v4
        with:
          name: Package
          path: build

  deploy-docker-image:
    runs-on: ubuntu-latest
    needs: build-test-package

    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v4
        with:
          name: Package
          path: target/

      - name: Generate image tag
        id: date
        run: echo "::set-output name=date::$(date +%Y%m%d-%H%M%S)"

      - name: Docker build
        run: docker build . -t iideveloper21/measurements-spring:$TAG_NAME
        env:
          TAG_NAME: CD-${{ steps.date.outputs.date }}

      - name: Retag to latest
        run: docker tag iideveloper21/measurements-spring:$TAG_NAME iideveloper21/measurements-spring:latest
        env:
          TAG_NAME: CD-${{ steps.date.outputs.date }}

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASS }}

      - name: Docker push
        run: docker push iideveloper21/measurements-spring:$TAG_NAME && docker push iideveloper21/measurements-spring:latest
        env:
          TAG_NAME: CD-${{ steps.date.outputs.date }}

  deliver-on-azure:
    runs-on: ubuntu-latest
    needs: deploy-docker-image

    steps:
      - name: Deploy to MS Azure
        run: echo "Deployed to MS Azure"
